image: node:18

stages:
  - install
  - build
  - test
  - deploy

install:
  stage: install
  script:
    - npm pkg delete scripts.prepare
    - npm ci
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    untracked: true
    expire_in: 30 mins
    paths:
      - node_modules

lint:
  stage: test
  script:
    - npm run lint
  dependencies:
    - install
  needs:
    - install

test:
  stage: test
  script:
    - npm run test
  dependencies:
    - install
  needs:
    - install
#build-packages:
#  stage: build
#  script:
#    - npm run build
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
#    untracked: true
#    expire_in: 1 days
#    paths:
#      - packages/**/*
#  dependencies:
#    - install
#  needs:
#    - install

#build-storybook:
#  stage: build
#  script:
#    - npm run storybook:build
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
#    untracked: true
#    expire_in: 1 days
#    paths:
#      - storybook/storybook-static
#  dependencies:
#    - install
#  needs:
#    - install

#deploy-storybook:
#  stage: deploy
#  script:
#    - deploy storybook/deploy.yaml
#  only:
#    - main
#  dependencies:
#    - build-storybook
#  needs:
#    - install
#    - build-storybook
