default:
  image: node:24.16.0
  interruptible: true
  artifacts:
    expire_in: 1 days

include:
  - component: gitlab.sikt.no/platon/ci-components/docker/docker@4.0.0
    inputs:
      image: $CI_REGISTRY_IMAGE
      image-tag: $CI_REGISTRY_TAG
  - component: gitlab.sikt.no/platon/ci-components/imagescan/imagescan@4.1.0
    inputs:
      image: $CI_REGISTRY_IMAGE
      image-tag: $CI_REGISTRY_TAG
  - component: gitlab.sikt.no/platon/ci-components/deploy/deploy@2.0.7
    inputs:
      prod-domain: "designsystem.sikt.no"
      test-id: "komponentbibliotek"
  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/vuln.gitlab-ci.yml
  - local: .gitlab/ci/build.gitlab-ci.yml
  - local: .gitlab/ci/deploy.gitlab-ci.yml
  - local: .gitlab/ci/release.gitlab-ci.yml
  - local: .gitlab/ci/figma.gitlab-ci.yml

variables:
  CI_REGISTRY_TAG: $CI_COMMIT_SHA-$CI_PIPELINE_ID
  HTTP_PORT: "80"
  REPLICAS: "1"
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

.npm_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull

workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

stages:
  - .pre
  - build
  - test
  - deploy
  - .post

install:
  stage: .pre
  extends: .npm_cache
  script:
    - npm pkg delete scripts.prepare
    - npm pkg delete scripts.postinstall
    - npm ci --no-audit --no-fund --cache .npm
    - npm audit signatures
  cache:
    policy: pull-push
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: on_success
