server {
  listen 80;
  server_name localhost;
  absolute_redirect off;
  root /usr/share/nginx/html;

  location = /komponenter {
    rewrite ^([^.]*[^/])$ $1/ permanent;
  }

  location = /retningslinjer {
    rewrite ^([^.]*[^/])$ $1/ permanent;
  }

  location /retningslinjer/ {
    return 307 https://www.figma.com/proto/6AVtxjDULlUdl9F4JEHAfv/Komponentbibliotek-v1.0?page-id=3716%3A12831&type=design&node-id=8599-15818&viewport=986%2C9159%2C0.26&t=QwVCdesNsGPVlTuE-1&scaling=min-zoom&starting-point-node-id=8599%3A15818&hide-ui=1;
  }

  location = /grunnleggende {
    rewrite ^([^.]*[^/])$ $1/ permanent;
  }

  location /grunnleggende/ {
    return 307 https://www.figma.com/proto/6AVtxjDULlUdl9F4JEHAfv/Komponentbibliotek-v1.0?page-id=3716%3A12831&type=design&node-id=8604-18505&viewport=986%2C9159%2C0.26&t=QwVCdesNsGPVlTuE-1&scaling=min-zoom&starting-point-node-id=8599%3A15818&hide-ui=1;
  }

  location = /monstre {
    rewrite ^([^.]*[^/])$ $1/ permanent;
  }

  location /monstre/ {
    return 307 https://www.figma.com/file/6AVtxjDULlUdl9F4JEHAfv/Komponentbibliotek-v1.0?type=design&node-id=1492-6437&mode=design&t=oT1QKjlQkPRrAxzc-0;
  }
}
