server {
  listen 80;
  server_name localhost;
  absolute_redirect off;
  root /usr/share/nginx/html;

  location = /komponenter {
    rewrite ^([^.]*[^/])$ $1/ permanent;
  }

  location = /retningslinjer {
    rewrite ^([^.]*[^/])$ $1/ permanent;
  }

  location /retningslinjer/ {
    return 307 https://www.figma.com/proto/6AVtxjDULlUdl9F4JEHAfv/Komponentbibliotek-v0.1?node-id=2686-9914&scaling=scale-down&page-id=473%3A5830&starting-point-node-id=2686%3A9914;
  }
}
