server {
  listen 80;
  server_name localhost;
  absolute_redirect off;
  root /usr/share/nginx/html;

  location = /storybook {
    rewrite ^([^.]*[^/])$ $1/ permanent;
  }

  location = /monstre {
    rewrite ^([^.]*[^/])$ $1/ permanent;
  }

  location /monstre/ {
    return 307 https://www.figma.com/file/6AVtxjDULlUdl9F4JEHAfv/Komponentbibliotek-v1.0?type=design&node-id=1492-6437&mode=design&t=oT1QKjlQkPRrAxzc-0;
  }
}
