export const config = [
  { id: "user-circle", name: "user-profile", category: "ui" },
  { id: "gear", name: "settings", category: "ui" },
  { id: "magnifying-glass", name: "search", category: "ui" },
  { id: "link-simple", name: "link", category: "ui" },
  { id: "bell", name: "notification", category: "ui" },
  { id: "lock-simple", name: "locked-closed", category: "ui" },
  { id: "lock-simple-open", name: "unlocked-open", category: "ui" },
  { id: "password", name: "password", category: "ui" },
  { id: "question", name: "help", category: "ui" },
  { id: "user-circle-plus", name: "user-add", category: "ui" },
  { id: "user-circle-minus", name: "user-remove", category: "ui" },
  { id: "sparkle", name: "ai", category: "ui" },
  { id: "arrow-right", name: "navigate-to-next", category: "navigation" },
  {
    id: "arrow-circle-right",
    name: "navigate-to-next-alt",
    category: "navigation",
  },
  { id: "arrow-left", name: "navigate-to-previous", category: "navigation" },
  {
    id: "arrow-circle-left",
    name: "navigate-to-previous-alt",
    category: "navigation",
  },
  {
    id: "arrow-square-out",
    name: "navigate-to-external",
    category: "navigation",
  },
  { id: "caret-right", name: "move-to-next", category: "navigation" },
  {
    id: "caret-circle-right",
    name: "move-to-next-alt",
    category: "navigation",
  },
  { id: "caret-left", name: "move-to-previous", category: "navigation" },
  {
    id: "caret-circle-left",
    name: "move-to-previous-alt",
    category: "navigation",
  },
  { id: "caret-up", name: "collapse-hide", category: "navigation" },
  { id: "caret-circle-up", name: "collapse-hide-alt", category: "navigation" },
  { id: "caret-down", name: "expand-show", category: "navigation" },
  {
    id: "caret-circle-down",
    name: "expand-show-alt",
    category: "navigation",
  },
  { id: "dots-three", name: "contextual-menu", category: "navigation" },
  {
    id: "dots-three-circle",
    name: "contextual-menu-alt",
    category: "navigation",
  },
  { id: "list", name: "menu", category: "navigation" },
  { id: "house", name: "home-landing", category: "navigation" },
  { id: "plus", name: "add", category: "action" },
  { id: "plus-circle", name: "add-alt", category: "action" },
  { id: "minus", name: "subtract", category: "action" },
  { id: "minus-circle", name: "subtract-alt", category: "action" },
  { id: "check", name: "confirm", category: "action" },
  { id: "x", name: "cancel", category: "action" },
  { id: "export", name: "export", category: "action" },
  { id: "copy", name: "copy", category: "action" },
  { id: "pencil", name: "edit", category: "action" },
  { id: "trash", name: "delete", category: "action" },
  { id: "arrow-u-up-left", name: "undo", category: "action" },
  { id: "arrow-u-up-right", name: "redo", category: "action" },
  { id: "floppy-disk", name: "save", category: "action" },
  { id: "sign-in", name: "sign-in", category: "action" },
  { id: "sign-out", name: "sign-out", category: "action" },
  { id: "upload-simple", name: "upload", category: "action" },
  { id: "download-simple", name: "download", category: "action" },
  { id: "bookmark-simple", name: "bookmark-unchecked", category: "action" },
  { id: "bookmark-simple-fill", name: "bookmark-checked", category: "action" },
  { id: "arrow-clockwise", name: "refresh", category: "action" },
  { id: "chat-text", name: "message", category: "communication" },
  { id: "phone", name: "phone", category: "communication" },
  { id: "envelope", name: "email", category: "communication" },
  { id: "calendar-blank", name: "date-calendar", category: "time-and-date" },
  { id: "calendar-plus", name: "add-to-calendar", category: "time-and-date" },
  { id: "clock", name: "time", category: "time-and-date" },
  { id: "paperclip", name: "attachment", category: "files" },
  { id: "image", name: "image-placeholder", category: "files" },
  { id: "folder", name: "folder", category: "files" },
  { id: "folder-plus", name: "create-folder", category: "files" },
  {
    id: "sort-ascending",
    name: "sort-ascending",
    category: "sorting-and-filtering",
  },
  {
    id: "sort-descending",
    name: "sort-descending",
    category: "sorting-and-filtering",
  },
  { id: "sliders", name: "adjust-settings", category: "sorting-and-filtering" },
  { id: "funnel", name: "filter", category: "sorting-and-filtering" },
  {
    id: "dots-six-vertical",
    name: "reorder-handle",
    category: "sorting-and-filtering",
  },
  { id: "check-circle", name: "success", category: "status" },
  { id: "info", name: "info", category: "status" },
  { id: "warning", name: "alert", category: "status" },
  { id: "x-circle", name: "failed", category: "status" },
  {
    id: "shopping-cart",
    name: "shopping-cart-selected-items",
    category: "menu",
  },
  { id: "megaphone", name: "feedback", category: "menu" },
  { id: "archive", name: "archive", category: "menu" },
  { id: "map-pin", name: "location", category: "map" },
  { id: "spinner-gap", name: "spinner-gap", category: "ui" },
  { id: "book", name: "book", category: "categorization" },
  { id: "law", source: "sds", name: "law", category: "categorization" },
  {
    id: "linked-in",
    source: "sds",
    name: "linked-in",
    category: "social-media",
  },
];
