const storybookUrl = `${import.meta.env.PUBLIC_STORYBOOK_URL}`;

export const components = [
  {
    id: "alert",
    name: "Alert",
    url: `${storybookUrl}?path=/docs/components-message-alert--docs`,
    storybook: `${storybookUrl}?path=/docs/components-message-alert--docs`,
  },
  {
    id: "application-status",
    name: "Application Status",
    url: `${storybookUrl}?path=/docs/components-message-application-status--docs`,
    storybook: `${storybookUrl}?path=/docs/components-message-application-status--docs`,
  },
  {
    id: "badge",
    name: "Badge",
    url: `${storybookUrl}?path=/docs/components-badge--docs`,
    figma:
      "https://www.figma.com/design/RMhyuuEhXZ4vbKVrLQr4t4/SDS-Komponentbibliotek-2.0.0?node-id=13122-2522",
    storybook: `${storybookUrl}?path=/docs/components-badge--docs`,
  },
  {
    id: "breadcrumbs",
    name: "Breadcrumbs",
    url: `${storybookUrl}?path=/docs/components-breadcrumbs--docs`,
    figma:
      "https://www.figma.com/design/RMhyuuEhXZ4vbKVrLQr4t4/SDS-Komponentbibliotek-2.0.0?node-id=13122-8446",
    storybook: `${storybookUrl}?path=/docs/components-breadcrumbs--docs`,
  },
  {
    id: "button",
    name: "Button",
    url: `${storybookUrl}?path=/docs/components-button-button--docs`,
    figma:
      "https://www.figma.com/design/RMhyuuEhXZ4vbKVrLQr4t4/SDS-Komponentbibliotek-2.0.0?node-id=13122-9882",
    storybook: `${storybookUrl}?path=/docs/components-button-button--docs`,
  },
  {
    id: "card",
    name: "Card",
    url: `${storybookUrl}?path=/docs/components-card--docs`,
    figma:
      "https://www.figma.com/design/RMhyuuEhXZ4vbKVrLQr4t4/SDS-Komponentbibliotek-2.0.0?node-id=13122-14044",
    storybook: `${storybookUrl}?path=/docs/components-card--docs`,
  },
  {
    id: "checkbox",
    name: "Checkbox",
    url: `${storybookUrl}?path=/docs/components-checkbox-checkbox--docs`,
    storybook: `${storybookUrl}?path=/docs/components-checkbox-checkbox--docs`,
  },
  {
    name: "Combobox",
    url: `${storybookUrl}?path=/docs/components-combobox--docs`,
    storybook: `${storybookUrl}?path=/docs/components-combobox--docs`,
  },
  {
    id: "input-datepicker",
    name: "Datepicker Input",
    url: `${storybookUrl}?path=/docs/components-inputdatepicker--docs`,
    storybook: `${storybookUrl}?path=/docs/components-inputdatepicker--docs`,
  },
  {
    id: "details",
    name: "Details",
    url: `${storybookUrl}?path=/docs/components-details--docs`,
    storybook: `${storybookUrl}?path=/docs/components-details--docs`,
  },
  {
    id: "dialog",
    name: "Dialog",
    url: `${storybookUrl}?path=/docs/components-dialog--docs`,
    storybook: `${storybookUrl}?path=/docs/components-dialog--docs`,
  },
  {
    id: "error-summary",
    name: "Error Summary",
    url: `${storybookUrl}?path=/docs/components-message-error-summary--docs`,
    storybook: `${storybookUrl}?path=/docs/components-message-error-summary--docs`,
  },
  {
    id: "input-file",
    name: "File Input",
    url: `${storybookUrl}?path=/docs/components-inputfile--docs`,
    storybook: `${storybookUrl}?path=/docs/components-inputfile--docs`,
  },
  {
    id: "filter-list",
    name: "Filter List",
    url: `${storybookUrl}?path=/docs/components-filterlist--docs`,
    storybook: `${storybookUrl}?path=/docs/components-filterlist--docs`,
  },
  {
    id: "footer",
    name: "Footer",
    url: `${storybookUrl}?path=/docs/components-footer--docs`,
    storybook: `${storybookUrl}?path=/docs/components-footer--docs`,
  },
  {
    id: "guide-panel",
    name: "Guide Panel",
    url: `${storybookUrl}?path=/docs/components-message-guide-panel--docs`,
    storybook: `${storybookUrl}?path=/docs/components-message-guide-panel--docs`,
  },
  {
    id: "header",
    name: "Header",
    url: `${storybookUrl}?path=/docs/components-header--docs`,
    storybook: `${storybookUrl}?path=/docs/components-header--docs`,
  },
  {
    id: "heading",
    name: "Heading",
    url: `${storybookUrl}?path=/docs/core-heading--docs`,
    storybook: `${storybookUrl}?path=/docs/core-heading--docs`,
  },
  {
    id: "link",
    name: "Link",
    url: `${storybookUrl}?path=/docs/core-link--docs`,
    storybook: `${storybookUrl}?path=/docs/core-link--docs`,
  },
  {
    id: "list",
    name: "List",
    url: `${storybookUrl}?path=/docs/components-list-unordered--docs`,
    storybook: `${storybookUrl}?path=/docs/components-list-unordered--docs`,
  },
  {
    id: "logo",
    name: "Logo",
    url: `${storybookUrl}?path=/docs/components-logo--docs`,
    storybook: `${storybookUrl}?path=/docs/components-logo--docs`,
  },
  {
    id: "pagination",
    name: "Pagination",
    url: `${storybookUrl}?path=/docs/components-pagination--docs`,
    storybook: `${storybookUrl}?path=/docs/components-pagination--docs`,
  },
  {
    id: "paragraph",
    name: "Paragraph",
    url: `${storybookUrl}?path=/docs/core-paragraph--docs`,
    storybook: `${storybookUrl}?path=/docs/core-paragraph--docs`,
  },
  {
    id: "popover",
    name: "Popover",
    url: `${storybookUrl}?path=/docs/components-popover--docs`,
    storybook: `${storybookUrl}?path=/docs/components-popover--docs`,
  },
  {
    id: "progress-indicator",
    name: "Progress Indicator",
    url: `${storybookUrl}?path=/docs/components-progressindicator--docs`,
    ustorybookrl: `${storybookUrl}?path=/docs/components-progressindicator--docs`,
  },
  {
    id: "radio",
    name: "Radio",
    url: `${storybookUrl}?path=/docs/components-radio-radiofieldset--docs`,
    storybook: `${storybookUrl}?path=/docs/components-radio-radiofieldset--docs`,
  },
  {
    id: "screen-reader-only",
    name: "Screen Reader Only",
    url: `${storybookUrl}?path=/docs/core-screenreaderonly--docs`,
    storybook: `${storybookUrl}?path=/docs/core-screenreaderonly--docs`,
  },
  {
    id: "section",
    name: "Section",
    url: `${storybookUrl}?path=/docs/components-section--docs`,
    storybook: `${storybookUrl}?path=/docs/components-section--docs`,
  },
  {
    id: "select",
    name: "Select",
    url: `${storybookUrl}?path=/docs/components-select--docs`,
    storybook: `${storybookUrl}?path=/docs/components-select--docs`,
  },
  {
    id: "table",
    name: "Table",
    url: `${storybookUrl}?path=/docs/components-table--docs`,
    storybook: `${storybookUrl}?path=/docs/components-table--docs`,
  },
  {
    id: "tabs",
    name: "Tabs",
    url: `${storybookUrl}?path=/docs/components-tabs--docs`,
    storybook: `${storybookUrl}?path=/docs/components-tabs--docs`,
  },
  {
    id: "text-area",
    name: "Text Area",
    url: `${storybookUrl}?path=/docs/components-input-textarea--docs`,
    storybook: `${storybookUrl}?path=/docs/components-input-textarea--docs`,
  },
  {
    id: "input-text",
    name: "Text Input",
    url: `${storybookUrl}?path=/docs/components-input-text--docs`,
    storybook: `${storybookUrl}?path=/docs/components-input-text--docs`,
  },
  {
    id: "toggle-button",
    name: "Toggle Button",
    url: `${storybookUrl}?path=/docs/components-toggle-togglebutton--docs`,
    storybook: `${storybookUrl}?path=/docs/components-toggle-togglebutton--docs`,
  },
  {
    id: "toggle-segment",
    name: "Toggle Segment",
    url: `${storybookUrl}?path=/docs/components-toggle-togglesegment--docs`,
    storybook: `${storybookUrl}?path=/docs/components-toggle-togglesegment--docs`,
  },
  {
    id: "toggle-switch",
    name: "Toggle Switch",
    url: `${storybookUrl}?path=/docs/components-toggle-toggleswitch--docs`,
    storybook: `${storybookUrl}?path=/docs/components-toggle-toggleswitch--docs`,
  },
  {
    id: "tooltip",
    name: "Tooltip",
    url: `${storybookUrl}?path=/docs/components-popover--docs#tooltip`,
    storybook: `${storybookUrl}?path=/docs/components-popover--docs#tooltip`,
  },
];
