map $http_origin $allow_origin {
  ~^https?://(.*\.)?sikt.no(:\d+)?$ $http_origin;
  ~^https?://(.*\.)?localhost(:\d+)?$ $http_origin;
  default "";
}

server {
  listen 80;
  server_name localhost;
  error_page 403 =404 /404.html;
  error_page 404 /404.html;
  error_page 500 /500.html;
  absolute_redirect off;
  root /usr/share/nginx/html;

  gzip on;
  gzip_min_length 1000;
  gzip_types
    application/javascript
    application/json
    application/manifest+json
    application/xml
    font/woff
    font/woff2
    image/svg+xml
    text/css
    text/javascript
    text/plain
    text/xml;

  include headers.conf;
  add_header Content-Security-Policy "default-src 'self'; connect-src 'self' https://matomo.sikt.no/ ws: wss:; script-src 'self' https://matomo.sikt.no/ 'unsafe-inline' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' https://static.sikt.no/; img-src 'self' https://matomo.sikt.no/ data:; media-src 'self'; frame-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; object-src 'none'; worker-src blob:; upgrade-insecure-requests;" always;
  add_header X-Frame-Options "DENY" always;

  location / {
    try_files $uri $uri/ =404;
  }

  location = /storybook {
    rewrite ^([^.]*[^/])$ $1/ permanent;
  }

  location /storybook/ {
    include headers.conf;
    add_header Access-Control-Allow-Origin $allow_origin always;
    add_header Content-Security-Policy "default-src 'self'; connect-src 'self' https://matomo.sikt.no/ ws: wss:; script-src 'self' https://matomo.sikt.no/ 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' https://static.sikt.no/ data:; img-src 'self' https://matomo.sikt.no/ data: blob:; media-src 'self'; frame-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'; object-src 'none'; worker-src 'self' blob:; upgrade-insecure-requests;" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
  }
}
