.tag:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG

release-prepare:
  stage: .pre
  extends: .tag
  before_script:
    # INFO: Get package name from git tag (without the npm organization (@sikt), pre- (sds-) / postfix (-sds) and version number (@*.*.*))
    - PACKAGE_NAME=$(echo "$CI_COMMIT_TAG" | sed -e "s/^@sikt\/sds-//" -e "s/^@sikt\///" -e "s/-sds@[0-9]*.[0-9]*.[0-9]*$//" -e "s/@[0-9]*.[0-9]*.[0-9]*$//")
  script:
    - echo "PACKAGE_NAME=$PACKAGE_NAME" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

release:
  stage: .post
  extends: .tag
  image: registry.gitlab.com/gitlab-org/cli:latest
  before_script:
    - RELEASE_NOTES=$(cat "./packages/${PACKAGE_NAME}/CHANGELOG.md" | awk '/^## / && !f {f=1; print; next} /^## / && f {exit} f')
  script:
    - echo "Release $CI_COMMIT_TAG"
    - echo "$RELEASE_NOTES" >> release_notes.md
  release:
    tag_name: $CI_COMMIT_TAG
    description: "./release_notes.md"
  dependencies:
    - release-prepare
  needs:
    - release-prepare

publish-npm:
  stage: .post
  extends: .tag
  id_tokens:
    VAULT_ID_TOKEN:
      aud: $VAULT_SERVER_URL
  secrets:
    NPM_TOKEN:
      vault: "gitlab/${CI_PROJECT_PATH}/npm-token@secret"
      token: $VAULT_ID_TOKEN
      file: false
  before_script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
  script:
    - npm publish --workspace=packages/${PACKAGE_NAME} --access public
  dependencies:
    - packages
    - release-prepare
  needs:
    - packages
    - release-prepare
    - release

release-report:
  stage: .post
  extends: .tag
  before_script:
    - RELEASE_NOTES=$(cat "./packages/${PACKAGE_NAME}/CHANGELOG.md" | awk '/^## / && !f {f=1; print; next} /^## / && f {exit} f')
  script:
    - >
      curl --request POST --header "Content-Type: application/json" --data "{\"text\":\"Release <https://${CI_SERVER_HOST}/${CI_PROJECT_PATH}/-/releases/${CI_COMMIT_TAG}|$CI_COMMIT_TAG> succeeded on $CI_COMMIT_BRANCH <$CI_PIPELINE_URL|$CI_PIPELINE_ID>\n\n\`\`\`${RELEASE_NOTES}\`\`\`\"}" "${SLACK_WEBHOOK_URL_PUBLIC}"
  dependencies:
    - release-prepare
  needs:
    - release-prepare
    - publish-npm
